version: "3.9"

services:
  caddy_server:
    image: caddy:2
    restart: always
    ports:
      - 80:80
    volumes:
      - ${PWD}/Caddyfile:/etc/caddy/Caddyfile
      - ./data:/data
      - ${PWD}/config:/config

  memos:
    image: neosmemo/memos:stable
    container_name: memos
    ports:
      - "5230:5230"
    volumes:
      - ./data/memos:/var/opt/memos
    restart: unless-stopped

networks:
  default:
    external: true
    name: app

