version: "3.9"

services:
  gitness:
    container_name: gitness
    image: harness/gitness:latest
    ports:
      - 3000:3000 
    volumes:
      - "./data:/data "
      - "/var/run/docker.sock:/var/run/docker.sock"

