version: "3.7"
services:
  nifi:
    image: apache/nifi:latest
    container_name: nifi
    ports:
      - 9090:9090
    environment:
      - NIFI_WEB_HTTP_PORT=9090
    volumes:
      - /tmp/nifi:/tmp/nifi

networks:
  default:
    external: true
    name: app

