version: "3.7"
services:
  mysql57:
    image: mysql:5.7
    container_name: mysql-5.7
    env_file: ./.env
    security_opt:
      - seccomp=unconfined
    ports:
      - 3306:3306
    networks:
      - db
    volumes:
      - /data/mysql/data:/var/lib/mysql:rw
      - /data/mysql/mysql-files:/var/lib/mysql-files:rw
      - ./conf:/etc/mysql/conf.d
    restart: always

  adminer:
    image: adminer
    networks:
      - app
    ports:
      - 8008:8080
    restart: always

networks:
  db:
    external: true
    name: db
  app:
    external: true
    name: app
