version: "3.7"
services:
  mysql57:
    image: mysql:5.7
    container_name: mysql-5.7
    env_file: ${PWD}/.env
    ports:
      - 3306:3306
    networks:
      - db
    volumes:
      - /data/mysql/data:/var/lib/mysql
      - /data/mysql/mysql-files:/var/lib/mysql-files
      - ${PWD}/conf:/etc/mysql/conf.d

  adminer:
    image: adminer
    networks:
      - app
    ports:
      - 8008:8080

networks:
  db:
    external: true
    name: db
  app:
    external: true
    name: app