version: "3.9"


services:
  nextcloud_base:
    image: nextcloud:stable
    container_name: nextcloud_base
    restart: always
    volumes:
    - ./data/data:/var/www/html
    environment:
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: 123456
    ports:
    - '8083:80'
