version: "3.7"
services:
  services: 
    image: redis:6
    container_name: redis6
    ports: 
      - 6380:6379
    volumes: 
      - redis_data:/redis
      
volumes: 
  redis_data:

networks: 
  default:
    external: 
      name: db