version: "3.9"

services:
  influxdb:
    image: influxdb:2
    ports:
      - "8086:8086"
    volumes:
      - ./data/data:/var/lib/influxdb2
      - ./data/config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=12345678
      - DOCKER_INFLUXDB_INIT_ORG=test
      - DOCKER_INFLUXDB_INIT_BUCKET=my_buck