version: "3.7"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: admin
    #   MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d/
      - /data/mongodb/data:/data/db
    # command:
    #   - '-f'
    #   - '/etc/mongod.conf'

    # volumes:
      # - ./mongod.conf:/etc/mongod.conf
      # - /data/mongodb/data:/data/db
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]

networks:
  default:
    external:
      name: db