version: "3.7"
services:
  es73:
    # https://www.elastic.co/guide/en/elasticsearch/reference/7.12/docker.html
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    container_name: es7
    environment:
      discovery.type: single-node  # https://www.elastic.co/guide/en/elasticsearch/reference/7.5/bootstrap-checks.html#single-node-discovery
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      transport.host: 127.0.0.1  # https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html#dev-vs-prod-mode
    logging:
      options:
          max-size: "200M"
          max-file: "3"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    # volumes:
    #   - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  # https://www.elastic.co/guide/en/kibana/current/docker.html
  kibana:
    image: docker.elastic.co/kibana/kibana:7.12.1
    container_name: kibana7
    environment:
      ELASTICSEARCH_HOSTS: http://es7:9200
    volumes:
      - ${PWD}/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    logging:
      options:
          max-size: "200M"
          max-file: "3"
    ports:
      - 5601:5601

networks:
  default:
    external: true
    name: db
