version: "3.7"

services:
  gitlab_runner:
    container_name: gitlab-runner
    image: gitlab/gitlab-runner:latest
    ports:
      - 8093:8093
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - gitlab_runner_config:/etc/gitlab-runner
    logging:
      options:
          max-size: "100M"
          max-file: "1"
    ulimits:
      memlock:
        soft: -1
        hard: -1

volumes: 
  gitlab_runner_config:

networks: 
  default:
    external: true
    name: other