version: "3.7"

services:
  gitlab_runner:
    container_name: gitlab-runner
    image: gitlab/gitlab-runner:latest
    ports:
      - 8093:8093
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - gitlab_runner_config:/etc/gitlab-runner

volumes: 
  gitlab_runner_config:

networks: 
  default:
    external: true
    name: other