version: "3.9"

services:
  jenkins:
    user: root
    container_name: jenkins
    image: jenkins/jenkins:latest
    ports:
      - 8085:8080
    volumes:
      - "./jenkins-docker-certs:/certs/client"
      - "./data:/var/jenkins_home"

