version: "3.7"
services:
  v2ray:
    image: v2fly/v2fly-core
    container_name: v2ray
    ports:
      - 1080:1080
    volumes:
      - ${PWD}/config.json:/etc/v2ray/config.json
    logging:
      options:
          max-size: "500M"
          max-file: "1"

  goproxy:
    build:
      context: .
    container_name: goproxy
    environment:
      SOCKS5_ADDR: v2ray:1080
      MAX_CONNECTIONS: 0
    ports:
      - 1081:1081
    logging:
      options:
          max-size: "500M"
          max-file: "1"
networks:
  default:
    external: true
    name: other

