version: "3.9"

x-base: &default-config
  restart: unless-stopped
  ulimits:
    nproc: 65535
    nofile:
      soft: 20000
      hard: 40000
  stop_grace_period: 1m
  logging:
    driver: json-file
    options:
      max-size: '100m'
      max-file: '1'
  mem_swappiness: 0


services:
  jupyterhub:
    # image: jupyterhub/jupyterhub:latest
    image: jupyterhub/singleuser:latest
    restart: "unless-stopped"
    container_name: jupyterhub
    ports:
      - 8888:8888
    volumes:
      - ./data/:/home/jovyan/work
