version: "3.7"
services:

  redisinsight:
    container_name: redisinsight
    image: redislabs/redisinsight
    ports:
      - 8001:8001
    volumes: 
      - redisinsight:/db

volumes: 
  redisinsight:

networks: 
  default:
    external:
      name: app